### ISSUE TITLE
Refactoring plan

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#527]
- [x] drop support for 3.6
- [x] drop cli.commands for some submodule init like in setup.py (must not negate the lazy loading though)
- [x] `die` calls should become a custom exception catched by the main #413
- [x] drop `__init__` for cli submodules, and make something abstract with escape hatch #487 
- [x] reidiomatize request calls #348
- [x] drop cchardet #511 
- [x] factorize exceptions in cli in same subpackage (example: YouTube, typically) #506 example `HypheCorpusAuthenticationError` (this dies, so easy)
- [x] upgrade pyinstaller and other relevant utilities
- [x] export cli main as an experiment (don't forget to adapt readme generation)
- [x] internalize and expose templating function for help
- [x] debug & improve lazyloading #533 
- [x] lazyloading should probably only happen for heavy deps, else it is too much of a drag
- [x] decorators for enrichers etc. #536 
- [x] don't forget `make readme`
- [x] rely on warnings for retryer logging and YT before sleep #542
- [x] create some helper decorators for enrichers and Twitter client #541 
- [x] investigate #548
